### ISSUE TITLE
Looking for info on how to use this.

### ISSUE THREAD

**Issue by smokey-live** [jomixlaf/NDI-Discovery-LXC#1]
This seems like exactly what I'm looking for.  I'm trying to set up NDI discovery server on a VM and be able to monitor it via a web interface but I'm struggling to figure out how to use this.  Please forgive my ignorance since there's no documentation.

My preference would be to install this as a container directly on my Proxmox server.  I also have an Ubuntu server running docker as well.  Can you provide brief instructions on how to use this script? As in what platform or base system I need to have to use it?

Thanks!

**Comment by jomixlaf** [comment]
Hi ! I wrote this many many months ago for a company I worked, I am not a programmer at all. Just a pationate into solving stuff like this edge case where I wanted to have an autonomous way to have a ultra quick and reliable NDI discovery server. 

I didnt even know my repo was public neither it could have interested someone. This is very new to me I will try to make a guide on how to use this. I will also modify this to avoid unrelated stuff in it. Give me a couple days and will do that for you.

**Comment by smokey-live** [comment]
I'm not really looking for a full on guide, just to know what kind of system you wrote the script for.  I'm kind of disecting it now to see if I can spin something up using what you wrote as a path.

**Comment by jomixlaf** [comment]
I just updated it right now including a little guide on how to use this in Debian. If you plan to use it in LXC container the NDI Disco server can be ready in less than a minute it's insane + you can see his real time data via the webpage 
IPSERVER/ndi-discovery-log.txt and everyday at 00:00 it self restart to create a new DIsco service. Hope that help

**Comment by smokey-live** [comment]
As you sent this reply I actually got it running on my Proxmox Server as an LXC.  This has been super helpful, i really appreciate it!

**Comment by jomixlaf** [comment]
Glad it help have fun ! 😎
